apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcore
      version: v1
  template:
    metadata:
      labels:
        app: aspnetcore
        version: v1
    spec:
      containers:
      - name: aspnetcore
        image: tejindermatharu/webapplication1:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  weather-service
      version: v1
  template:
    metadata:
      labels:
        app:  weather-service
        version: v1
    spec:
      containers:
      - name: weather-service
        image: tejindermatharu/webapi:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcore-service
  labels:
    app: aspnetcore
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  selector:
    app: aspnetcore
